services:
  _defaults:
    autowire: true
    autoconfigure: true

  AlmaviaCX\RestrictedSiteaccess\EventListener\AccessControlSubscriber:
    lazy: true
    tags:
      - { name: kernel.event_listener, event: kernel.request }
